stages:
  - test

playwright_tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.55.0-noble
  script:
    - npm ci --force # Installs project dependencies
    - npx playwright install --with-deps --force # Installs Playwright browsers and their dependencies
    - npm run pageObjects-chrome # Runs your Playwright tests
  artifacts:
    when: always
    paths:
      - playwright-report/ # Uploads the Playwright HTML report as an artifact
    expire_in: 1 day # Sets the expiration for the artifact